### ISSUE TITLE
Thermia Atlas 18 - Translation Error: The intl string context variable "model" was not provided to the string "Thermia Heatpump: {model}": 192.168.99.115:502

### ISSUE THREAD

**Issue by josbmw** [CJNE/thermiagenesis#113]
Hi Johan,

Thank you for this integration!

I have an Atlas 18, freshly installed.
Thermia integration is the latest version.

In the entities I get: [Translation Error: The intl string context variable "model" was not provided to the string "Thermia Heatpump: {model}": 192.168.99.115:502](http://homeassistant.local:8123/config/integrations#config_entry=703e8e6a71c5426c5f76ea8c4672edd0)

The entities show up, no problem and I can control the heatpump. But I'm missing some entries.
Can I add entries/modbus addresses myself somewhere?
I need the value of Address 47 De Facto Address 30048 HGW mix valve position.
In const.py I see a lot of the available variables, but I have no idea what's the relation between the modbus address and the variable or how to add extra variables.

Atlas was running Genesis 11, but I updated to Genesis 12 yesterday. The issue "Translation Error" persists.

Jos

**Comment by josbmw** [comment]
Hi Johan,

As far as I can see, it's available for the inverter and not for the mega. My heatpump is set to inverter.
![image](https://user-images.githubusercontent.com/40317530/176657059-588ba237-9d99-414d-912b-aef8f1d8e32d.png)

**Comment by CJNE** [comment]
Aha, then I probably made a misstake, will take a look asap!

**Comment by josbmw** [comment]
HGW is only for heatpumps with integrated boiler. The mega has no boiler, so no HGW.

**Comment by dkvk** [comment]
Hi,
I have a Diplomat Inverter Duo.

When setting up the integration, I get various intl-related error messages.

The first is shown already when searching for integrations to add:
<img width="617" alt="image" src="https://user-images.githubusercontent.com/1168561/188407491-2966284b-b7f8-43eb-a91a-dce1f74aeb35.png">

I can, anyway, select and add the integration and proceeding adding the pump despite more intl-related error messages in the UI.

The pump is correctly identified as the pump I have:
<img width="198" alt="image" src="https://user-images.githubusercontent.com/1168561/188408154-2ccabdb9-2d21-4819-9d00-fc5f80832bc8.png">

But most of the controls and all sensors are disabled. This is how it looks if I add all controls and sensors to a dashboard:
![image](https://user-images.githubusercontent.com/1168561/188408800-572b93e0-8cf8-4a65-9d6c-725cb954e9bc.png)


As it seems to be some intl-related errors shown I am thinking of this plugin has some required settings regarding language or anything related?

**Comment by dkvk** [comment]
Ok, I now realized that it was required to change the language of Home Assistant UI to Swedish to eliminate the intl-error messages :)

But I cannot see any other sensors or controls than shown in my previous message.

**Comment by dkvk** [comment]
And now I realized that I had to manually activate each sensor/control.

**Comment by dkvk** [comment]
Det gjorde jag inte. Som jag förstått är detta defaultvärdet när inget värde finns.

Då jag inte har någon innegivare så verkar det vara i sin ordning.

**Comment by Floppe** [comment]
#234 would fix the translation error.

**Comment by CJNE** [comment]
Should be OK now
