### ISSUE TITLE
För gammal Genesis sw?

### ISSUE THREAD

**Issue by frealv** [CJNE/thermiagenesis#118]
Har precis lyckats få igång BMS på min Atlas 18(tack vare en post om servicekoden i detta projekt...tack för det), men får problemet med "Translation Error: The intl string context..." i Homeassistant, vilket jag förstått kan ha att göra med att min sw i pumpen är för gammal(9.0). Så min fråga som inte direkt har med just detta projekt är: var får jag tag i firmware, samt hur uppgraderar jag? Ser att ssh är igång på pumpen...är det vägen att gå? vad är isf user/pass? Ledsen för att posta detta som en issue, men detta verkar vara stället för folk som kan sina pumpar...

**Comment by nhogblom** [comment]
Du har säkert löst detta redan, men problemet ligger i Home assistant.
Ändra språket i Homeassistant till Svenska så ska det funka för dig.

**Comment by gustavstrandberg** [comment]
Firmware i VP uppgraderar man via USB. Är du väl uppgraderad till version >11 så funkar OTA.
Jag kan skaka fram nyare firmware via en kontakt om du behöver.

**Comment by frealv** [comment]
Tack för svaret…hade inte löst det

**Comment by frealv** [comment]
@gustavstrandberg 
Jag tar gärna emot en nyare firmware…har uppgraderat det mesta i mina dagar, men detta blir min första vp 😀

**Comment by gustavstrandberg** [comment]
Skicka din mail till förnamn.efternamn@bredband.net (du ser i mitt handle ovan) så skickar jag firmware och instruktioner.

**Comment by frealv** [comment]
Hej.
Sorry att besvära, så kasta mailet om du tycker att jag är påträngande, ok?)
Har fått alla firmware 9->12 från min installatör(edekyl i Örebro), dock säger dom att min atlas 18 förmodligen behöver fabriksåterställas i samband med ug av fw… Vet du om det går att få ut samtliga parametrar via CJNE/pythermiagenesis Python script? Jag får ut ett antal värden, i huvudsak True/False-värden, men inte alla och i synnerhet inte olika sifferinställningar. I HA ser jag 327 entities, men det är ju ett elände att gå igenom dom i HA…vore skönt att kunna dumpa ut allt till en textfil :-)

**Comment by gustavstrandberg** [comment]
Tjena! Det är lungt.
Ingen aning hur man dumpar ut värdena, inget jag har testat.
Men jag har nöjt mig med att skriva ner värmekurvan och gå igenom det
basala i interfacet i pannan, skriva ner på papper och sedan uppgradera.
