### ISSUE TITLE
System Supply Line Temperature

### ISSUE THREAD

**Issue by Alphaemef** [CJNE/thermiagenesis#157]
Hi Guys. Tremendous work with this HA integration, its absolutely a wonderful tool, and extremely valuable. 

I have a Thermia Atlas 18, registered in the custom component as Inverter Duo. Most is working fine, but the "system Supply Line Temperature" is consistently showing 200 degrees celcius. In the API it shows an accurate temperature (24 degrees). Am I using the wrong sensor parameter name or did I mess some setting up?

**Comment by ejansson88** [comment]
I have the same problem as you, havent found any solution yet, please post if you find out whats wrong

**Comment by frealv** [comment]
Same here(Atlas 18). Tried to set "Target sensor" in Thermostat card to external thermometer, but no success .

**Comment by Alphaemef** [comment]
Found something that may solve this. 
The "Condenser Out" temperature and "Condenser In Temperature" matches pretty well with "Supply Line" and "Return Line". 

Im not sure if there are separate thermometers, but this is within 0,5-1 degrees of the actual supply and return line. So I'm using those for now.

**Comment by frealv** [comment]
Excelent find!
May I ask how you are using te sensors? I've tried to set the "Target Sensor" in the generic thermostat card, but no success.

**Comment by frealv** [comment]
Right...think first, ask later...
If anyone else wondering about this...to get the condenser_in_temperature to show in the generic thermostat card in HA:

edit the file ../custom_components/thermiagenesis/const.py to match the following:

    "heat": {
        ATTR_LABEL: "Heat",
        # ATTR_CURRENT_TEMPERATURE: ATTR_INPUT_SYSTEM_SUPPLY_LINE_CALCULATED_SET_POINT
        # ATTR_CURRENT_TEMPERATURE: thermiaconst.ATTR_INPUT_ROOM_TEMPERATURE_SENSOR,
        **ATTR_CURRENT_TEMPERATURE: thermiaconst.ATTR_INPUT_CONDENSER_IN_TEMPERATURE,**
        ATTR_TEMPERATURE: thermiaconst.ATTR_HOLDING_COMFORT_WHEEL_SETTING,
        ATTR_MIN_TEMP: 10,
        ATTR_MAX_TEMP: 40,
        ATTR_ENABLED: thermiaconst.ATTR_COIL_ENABLE_HEAT,
        ATTR_DEFAULT_ENABLED: True,
        KEY_STATUS_VALUE: "Heat",
    },

and restart HA. Häpp!

**Comment by frealv** [comment]
However...when boiling hot water, the condenser in temp goes WAY up, so then again...this might not be the answer after all...

**Comment by Alphaemef** [comment]
Yeah I think the only way to get around is, is by installing a TP sensor and feeding it into the thermostat card or by removing the tp showing altogether. 

There are no other sensors in the thermostat that provide anything meaningful.

**Comment by dd1982** [comment]
On the physical side of things - the pump only has a sensor for condenser in and condenser out - after the condenser the now hot water is either routed to the system supply line or through the tap water tank. If you want the actual system supply line temperature you need an additional sensor connected which is normally only installed when combining the pump with external heat sources. Without external heat source the supply line temp more or less the same thing as the condenser out _when the pump is in heating mode_ - while producing hot water the condenser temps say nothing about your heating systems supply line temp as the water is circulated elsewhere.
