### ISSUE TITLE
Set values through modbus

### ISSUE THREAD

**Issue by BarbaGrump** [CJNE/thermiagenesis#161]
I see that you are able to set values, for example which gear to be used when heating, using the ThermIQ-MQTT solution...is there a way to do this using this plugin over modbus TCP? I think modifying gears, curves, break-points etc would be a great addition. Or maybe this is already possible?  I have tried to set "Desired Gear For Heating" manually, but that doesn't work...

edit: consulting the user guide ” Modbus protocol for Genesis platform, v1.0” I think the values I’m interested in is in section “3.4. - Read/Write Analog Registers” and there to implement function 6(write)

**Comment by frealv** [comment]
In pythermiagenesis I see references to for example
ATTR_HOLDING_MINIMUM_ALLOWED_GEAR_IN_HEATING = "holding_minimum_allowed_gear_in_heating"
ATTR_HOLDING_MAXIMUM_ALLOWED_GEAR_IN_HEATING = "holding_maximum_allowed_gear_in_heating"
ATTR_HOLDING_MAXIMUM_ALLOWED_GEAR_IN_TAP_WATER = "holding_maximum_allowed_gear_in_tap_water"
ATTR_HOLDING_MINIMUM_ALLOWED_GEAR_IN_TAP_WATER = "holding_minimum_allowed_gear_in_tap_water"

I suppose its values like this I would like to be able to set through HA automation. Why? Well, I thinking like this: If the electricity price next hour is is over X, I want to boil hot-water 15 min before that hour. Its possible to do this already(set tapwater temp interval to 59-60) But I want to be sure that the highest gear is used to be sure its ready when the electricity price increases.

**Comment by dd1982** [comment]
Does raising the tapwater temp interval to 59-60 work for you? Tried setting the lower bound to 50 for a few hours on my Calibra when it was colder in the hot-water tank but for some reason that wasn't make it decide to heat up the water. Would also like to be able to choose maximum gear - if I let it heat a bit extra when prices are lower and turn off the heating entirely for a while when they're higher I don't want it to be in a rush to raise the supply line temp when I turn it back on again. 

![image](https://user-images.githubusercontent.com/2264629/205024094-fe29063a-ee9f-487b-9c69-8be37ef3a330.png)

**Comment by CJNE** [comment]
I'll have a look at fixing this, the missing piece is to have number entities for the holding registers, to allow reading and writing such values.

**Comment by BarbaGrump** [comment]
> Does raising the tapwater temp interval to 59-60 work for you? Tried setting the lower bound to 50 for a few hours on my Calibra when it was colder in the hot-water tank but for some reason that wasn't make it decide to heat up the water. Would also like to be able to choose maximum gear - if I let it heat a bit extra when prices are lower and turn off the heating entirely for a while when they're higher I don't want it to be in a rush to raise the supply line temp when I turn it back on again.
> 
> ![image](https://user-images.githubusercontent.com/2264629/205024094-fe29063a-ee9f-487b-9c69-8be37ef3a330.png)

It's working fine to set 55-60 on my Atlas 18 anyhows... not tried 59-60. With current price on electricity its mor 35-40... :-(

**Comment by BarbaGrump** [comment]
> I'll have a look at fixing this, the missing piece is to have number entities for the holding registers, to allow reading and writing such values.

That would be awsome! Thanks a lot for your effort!

**Comment by CJNE** [comment]
Fixed in 0.0.10, the entities are disabled by default, so you need to activate the ones you want to use (in the UI)

**Comment by BarbaGrump** [comment]
Thanks a lot for your work!
Works like a charm. One thought though: the slider(ex. comfort wheel) is very sensitive going from -40 to 100. Would it be possible to narrow it down to something like 15-40 or something?
