### ISSUE TITLE
Variable model was not provied - Connection Error

### ISSUE THREAD

**Issue by ehskha** [CJNE/thermiagenesis#171]
Hi, 

I have a Thermia Diplomat Inverter and I have downloaded and installed all the files here according to the instructions. 

When Adding the Integration, I see this error window. 

![image](https://user-images.githubusercontent.com/68080964/194487100-29ee998c-7da2-4e4f-bccf-6f25ebbcccd6.png)

Even after entering the IP-address, I get connection error. 
What am I doing wrong?

**Comment by nhogblom** [comment]
Change homeassistant language to Swedish and it will work.

**Comment by nhogblom** [comment]
You need to enable modbus TCP, you find this setting under installer settings/installatörs inställningar if i recall correctly.
The pump has to be in OFF setting to show this menu.

Above atleast apply on my Thermia Calibra, i would assume it is the same for your model.

**Comment by ehskha** [comment]
Thanks, Thats what I did and now it connects.
