### ISSUE TITLE
Read out total Kwh used

### ISSUE THREAD

**Issue by mumse** [CJNE/thermiagenesis#205]
Hi! Iam kind of new to this integration so bear with me ;) 
I am using this integration with our Thermia Atlas 3-12KW, i would like to read out the total energy consupmtion of the heat pump with "**sensor.electric_meter_kwh_total**" , i have enabled what i belive is everything related to energy usage but the readout of "**sensor.electric_meter_kwh_total**" is still zero...

Is there any way to get the sensor to read energy consumption? Maybe there are some settings i have not thaught about that needs to be modified..

**Comment by CJNE** [comment]
Hello!
The ability to read energy usage usually required an accessory installed, are you sure that this is installed?
Can you see energy usage somewhere in the display UI?

**Comment by mumse** [comment]
> Hello! The ability to read energy usage usually required an accessory installed, are you sure that this is installed? Can you see energy usage somewhere in the display UI?

Aha.. That might explain why I have no readouts.. Because as far as I know there are no accessories installed. Maybe I should consult with Thermia on what I need or just go with a third party option like Shelly or something similar. 
Thanks for the reply anyway 🙂
