### ISSUE TITLE
Unit issue for electric meter entities

### ISSUE THREAD

**Issue by Mi3czy** [CJNE/thermiagenesis#86]
The units for all energy related entities are °C
Instead of kWh,V,A,W,…

**Comment by Mi3czy** [comment]
Submitted change pull request with change for this..

**Comment by CJNE** [comment]
Thank you! I'm swamped with work at the moment but will have a look asap, I appreciate your contribution!

**Comment by Mi3czy** [comment]
The unit change works on my heatpump.
Still having some issues with the energy class tho (to add kwh to the energy dashboard)

**Comment by CJNE** [comment]
Hi @Mi3czy,

I can't find a PR with theses changes?

**Comment by CJNE** [comment]
I've release 0.0.8 with your PR, I also added the state class needed for it to work with the energy dashboard, I haven't been able to test it but I hope if works.

**Comment by Mi3czy** [comment]
Allright!
just tested it but the energy dashboard doesn't work yet

Op zo 8 mei 2022 om 18:54 schreef Johan Isacsson ***@***.***>:
